### ISSUE TITLE
Provide pre-compiled binaries

### ISSUE THREAD

**Issue by gabegorelick** [TooTallNate/node-weak#22]
I know this is [controversial](https://github.com/npm/npm/issues/1891), but can we get pre-compiled binaries? 

node-weak is the only dependency in my app (out of a few hundred) that requires my Windows developers to install the Visual Studio toolchain (a process that can kill a whole day wrangling C++ redistributals). It also means I have to pre-build before I ship to Windows clients.

**Comment by TooTallNate** [comment]
Sorry, but I'm in the camp that think that binaries belong at the package-manager level, as opposed to the module level.

A pre-build step isn't the end of the world for deployments. We do it at Cloudup for the Windows tray icon, and has never really gotten in the way.
