### ISSUE TITLE
npm install fails with io.js

### ISSUE THREAD

**Issue by jessetane** [TooTallNate/node-weak#39]
tried doing a nan bump, but that didn't seem to fix...

iojs/io.js#456

**Comment by deian** [comment]
https://github.com/GitStarInc/node-weak/compare/TooTallNate:98622b9...GitStarInc:b7e8087

**Comment by jessetane** [comment]
Ok just tried again, the newer nan version (1.5.3) does seem to work - not sure what happened the first time.

**Comment by jessetane** [comment]
@deian PR?

**Comment by TooTallNate** [comment]
Try out v0.3.4
