### ISSUE TITLE
weak.callbacks uses EventEmitter.listeners which returns array.slice

### ISSUE THREAD

**Issue by fastest963** [TooTallNate/node-weak#43]
The documentation for `weak.callbacks` says:
> The array can be `push()`ed or `unshift()`ed onto, to have more control over the execution order of the callbacks.

But looking at [`EventEmitter.prototype.listeners`](https://github.com/joyent/node/blob/master/lib/events.js#L299) it seems that listeners returns a slice of the actual events array so we can't use the result of `callbacks` to re-order or delete callbacks.

**Comment by TooTallNate** [comment]
Good point. I believe the listeners() behavior used to return the listeners array untouched, but that was changed in v0.10 to return a copy. Patch fixing the docs appreciated!

**Comment by fastest963** [comment]
Should I make `callbacks` return the underlying `_events` array or just fix the docs? If just a docs fix is preferred, would you be opposed to adding a `removeAllCallbacks` method?

**Comment by TooTallNate** [comment]
Maybe we should just expose a way to return the underlying EventEmitter?

**Comment by fastest963** [comment]
The only issue with that is the event name (`_CB`) is privately scoped. I'm making a PR let's move the discussion there. I think we're both in agreement that this issue is an issue and should be fixed someway or another.
