### ISSUE TITLE
Support 0.12 and 4.0 in the same version

### ISSUE THREAD

**Issue by robcolburn** [TooTallNate/node-weak#59]
To ease our transition paths, perhaps we could support for a time?

https://github.com/substack/dnode/pull/172#issuecomment-142454617

**Comment by TooTallNate** [comment]
v0.8 - v3 are currently being tested on Travis and passing the tests:
https://travis-ci.org/TooTallNate/node-weak/builds/76013777

What errors are you seeing?

**Comment by robcolburn** [comment]
Aha! 

It's npm issue, not a node issue.  I had some fun times there learning more about dealing with switching node/npm versions on my local machine, anyway… This seems be an issue with `npm@1.2.0` (which is the default for `nvm`'s node v0.8) when dependencies are specified with the `^` operator (the default for nvm's node v0.8).  `weak` has already compensated in travis config ( https://github.com/TooTallNate/node-weak/blob/master/.travis.yml#L24 ), but we'll need a likewise change to `dnone`.
