### ISSUE TITLE
FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope

### ISSUE THREAD

**Issue by Unterdrucker** [TooTallNate/node-weak#65]
Fatal error occurs in weak module, fix already exists
TooTallNate/node-weak@master...S-YOU:node5

More info: https://github.com/nodejs/node/issues/3598

**Comment by TooTallNate** [comment]
Do you have repro code for this? Node v5 appears to be passing still [according to Travis](https://travis-ci.org/TooTallNate/node-weak/jobs/92141775).

**Comment by S-YOU** [comment]
The error happen with node 5.0.0 when running prerender+phantomjs for me. 
There is a chance that 5.1.0 fix it somehow.

**Comment by e6nian** [comment]
@S-YOU 5.1.1 still has this problem

**Comment by TooTallNate** [comment]
Fixed by #67.
