### ISSUE TITLE
Warning on build that "NVM_NODEJS_ORG_MIRROR" is deprecated

### ISSUE THREAD

**Issue by isiahmeadows** [TooTallNate/node-weak#76]
```
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
```

**Comment by xandermathews** [comment]
I'm seeing that deprecation warning on several projects after updating to the latest LTS.
Since the warning is inside gyp, and this project has minimal surface-area with gyp, I suspect that this will be fixed in gyp and there's nothing that could or should be done in weak about this.

**Comment by isiahmeadows** [comment]
@xandermathews [It's node-gyp intentionally printing a deprecation warning.](https://github.com/nodejs/node-gyp/issues/942) [Here's the PR that changed it.](https://github.com/nodejs/node-gyp/pull/878)

**Comment by xandermathews** [comment]
Cool! thanks for the links; it's nice to understand the nvm/gyp goof that set up the situation.

But why does Weak need a ticket for this? 
The warning is simply indicative of using gyp inside a nvm shell, and Weak merely uses the already provided node/gyp/etc tooling.

While those using custom mirrors need to start setting the new variable before the relevant gyp upgrade, there's nothing here for Weak to compensate for.

**Comment by TooTallNate** [comment]
Closing since it's a node-gyp issue.

**Comment by isiahmeadows** [comment]
@TooTallNate [Not what I observed.](https://github.com/TooTallNate/node-weak/issues/76#issuecomment-269805924)

**Comment by xandermathews** [comment]
@isiahmeadows what did you intend to link in your last comment?

**Comment by isiahmeadows** [comment]
@xandermathews I fixed the link to point to the specific comment and commit.

**Comment by TooTallNate** [comment]
Well like nodejs/node-gyp#942 says, you need to upgrade your version of nvm and/or node-gyp. This is not related to node-weak. You'll see that if you try to install any other native module the same thing will happen (i.e. `npm install time`).
