### ISSUE TITLE
No Binary for Windows 64-bit and Weak 1.0.1

### ISSUE THREAD

**Issue by jaylandro** [TooTallNate/node-weak#85]
There is no pre-compiled binary available for Weak 1.0.1 on windows, causing all of our builds to require python for rebuild. Discovered this while installing Jest 22.0.4.

I would be glad to help if you can let me know where to publish the binary to.

**Comment by pleunv** [comment]
Running into the same issue. Weak is flagged as optionalDependency in the latest Jest but this tends to be quite noisy when compilation fails during npm install. As this is the only dep we have that requires a compilation toolchain I'd really like to avoid having to have everybody in the team go through setting this up properly on Windows as it's a very common source of frustration.

However, I don't think @TooTallNate is jumping to add binaries (https://github.com/facebook/jest/issues/5006).
